CUDA_VISIBLE_DEVICES=0 python /workspace/code/GenPose-main/GenPose-main/runners/trainer.py \
--data_path /workspace/code/data/PoseData \
--log_dir EnergyNet \
--agent_type energy \
--sampler_mode ode \
--batch_size 192 \
--eval_freq 1 \
--n_epochs 100 \
--selected_classes bottle bowl camera can laptop mug \
--percentage_data_for_train 1.0 \
--percentage_data_for_test 1.0 \
--percentage_data_for_val 1.0 \
--seed 0 \
--is_train \
